# -*- coding: utf-8 -*-
"""Summer Olympics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17cdBqCGMtwtjVqvy1XaiqpnA39bVqnZy
"""

import pandas as pd

df = pd.read_csv('summer.csv')

df

"""# Q1 - In how many cities Summer Olympics is held so far?"""

NumberOfCities = len(df['City'].unique())

data = []

for city in df['City'].unique():
  data.append(city)

print("The Olympics had been held in", NumberOfCities, "cities")
print("The 22 city names are as follows: ")
print(data)

"""# Q2 - Which sport is having most number of Gold Medals so far? (Top 5)"""

goldmedal = df[df['Medal'] == 'Gold']
sports_data = []
for sport in gold_medal['Sport'].unique():
  sports_data.append([sport,len(gold_medal[gold_medal['Sport'] == sport])])

sports_data = pd.DataFrame(sports,columns=['Sport','Gold_Medals'])
sports_data = sports.sort_values(by ='Gold_Medals', ascending = False)

print("Top 5 Sports with descending order of gold medals: ")
print(sports)

sports = sports.sort_values(by ='Gold_Medals', ascending = False).head()
sports.plot(x ='Sport',y ='Gold_Medals',kind = 'bar',figsize =(10,5),color = 'gold')

"""# Q3 - Which sport is having most number of medals so far? (Top 5)"""

most_medals = df.groupby('Sport').count()['Medal']

top5 = most_medals.sort_values(ascending = False).head()
print(top5)
print("Plot of Top 5 Sports having most no. of Medals is as Follows:\n")

top5.plot.pie(figsize =(10,5))

"""# Q4 - Which player has won most number of medals? (Top 5)"""

players_won = df.groupby('Athlete').count()['Medal']

top5players = players_won.sort_values(ascending = False).head()
print(top5players)
print("Plot of Top 5 Players having won the most no. of Medals is as Follows:\n")

top5players.plot.pie(figsize =(10,5))

best_player = top5players[0]
print("The best player is PHELPS, Michael with ", top5players[0] ,"medals")

"""# Q5 - Which player has won most number Gold Medals of medals? (Top 5)"""

gold_medal = df[df['Medal'] == 'Gold']
players_gold = gold_medal.groupby('Athlete').count()['Medal']

top5goldplayers = players_gold.sort_values(ascending = False).head()
print(top5goldplayers, "\n")

print(" 'PHELPS, Michael' Player has won most no. of Gold Medals - '18'\n ")

mostss.plot.area(figsize =(10,5))

"""# Q6 - In which year India won first Gold Medal in Summer Olympics?"""

Years = []
gold_medal = df[df['Medal'] == 'Gold']
India_year = gold_medal[gold_medal['Country'] =='IND']
Years.append(India_year['Year'].unique())

print("The years in which India won Gold Medal are :")
print(Years, "\n")

India_first = gold_medal[gold_medal['Country'] =='IND']['Year'].min()
Indian_year = str(India_first)

print("In the year "+ Indian_year + " India won First Gold Medal in Summer Olympics")

"""# Q7 - Which event is most popular in terms on number of players? (Top 5)"""

data = []
for events in df['Event'].unique():
  data.append([events,len(df[df['Event'] == events])])

data = pd.DataFrame(data,columns = ["Event","No_of_players"])
data = data.sort_values(by = "No_of_players",ascending = False).head()

print("The most popular events in terms of players is: \n")
print(data, "\n")
data.plot(x ='Event',y ='No_of_players',kind = 'line',figsize =(10,5),color = 'magenta')


#We can use groupby function :
#df.groupby("Event").count()["Athlete"].sort_values(ascending = False).head(10).plot.bar(figsize = (15,7))

"""# Q8 - Which sport is having most female Gold Medalists? (Top 5)"""

gold_medal = df[df['Medal'] == 'Gold']
Female_Gold = gold_medal[gold_medal['Gender'] == 'Women']

data = []
for fem in Female_Gold['Sport'].unique():
  data.append([fem, len(Female_Gold[Female_Gold['Sport'] == fem])])

data = pd.DataFrame(data,columns = ["Sport","Female_Gold_Medalists"])
data = data.sort_values(by = "Female_Gold_Medalists",ascending = False).head(20)        # To know all Female Gold Medalists remove 20 from .head(20)

print("Sports having most No. of Female Gold Medalists are as follows :")

print(data, "\n")

data = data.sort_values(by = "Female_Gold_Medalists",ascending = False).head(5)
print(data, "\n")
data.plot(x ='Sport',y ='Female_Gold_Medalists',kind = 'bar',figsize =(10,5), color = "green")